20:57:47.240 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - not:1
20:57:47.242 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - total:1
20:57:47.242 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - and:13
20:57:47.242 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - of:3
20:57:47.242 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - generous:1
20:57:47.242 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - hard:1
20:57:47.242 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - on:2
20:57:47.243 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - No:1
20:57:47.243 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - spent:1
20:57:47.243 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - match:1
20:57:47.243 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - was:5
20:57:47.243 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - enough:1
20:57:47.243 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - demanding:1
20:57:47.243 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - grew:1
20:57:47.243 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - below
But:1
20:57:47.244 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - regretful:1
20:57:47.244 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - there:1
20:57:47.244 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - time:2
20:57:47.244 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - world
Feeling:1
20:57:47.244 [main] INFO  com.solvd.itcompany.readtext.ReadTextFromFile - he:1
21:15:49.267 [pool-2-thread-3] ERROR com.solvd.itcompany.connectionpool.ThreadAndRunnableDemo - Error in task execution: 
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at java.sql.DriverManager.getConnection(DriverManager.java:683) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:230) ~[java.sql:?]
	at com.solvd.itcompany.connectionpool.ConnectionPoolDesign.createConnection(ConnectionPoolDesign.java:74) ~[classes/:?]
	at com.solvd.itcompany.connectionpool.ConnectionPoolDesign.getConnection(ConnectionPoolDesign.java:38) ~[classes/:?]
	at com.solvd.itcompany.connectionpool.ThreadAndRunnableDemo.lambda$main$0(ThreadAndRunnableDemo.java:31) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	... 13 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:576) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:666) ~[?:?]
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:948) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:818) ~[mysql-connector-j-8.0.31.jar:8.0.31]
	... 13 more
